apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-view
spec:
  selector:
    matchLabels:
      app: post-view
  template:
    metadata:
      labels:
        app: post-view
    spec:
      containers:
      - image: joshferrellvmw/post-view:latest
        name: post-view
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
        securityContext:
          runAsUser: 65534
---
apiVersion: v1
kind: Service
metadata:
  name: post-view
spec:
  selector:
    app: post-view
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 8080
